In [8]:
# coding:utf-8  
'''
@author: Jason.F
@data: 2019.08.16
@function: eICU-CRD database: https://eicu-crd.mit.edu/ 
           schema of DB: https://mit-lcp.github.io/eicu-schema-spy/
           Github: https://github.com/mit-lcp/eicu-code
'''
import numpy as np
import pandas as pd

'''
Table: admissionDrug
admissiondrugid - primary key, has no meaning but identifies rows uniquely
drugOffset - number of minutes from unit admit time that the admission drug was administered
drugEnteredOffset - number of minutes from unit admit time that the admission drug was entered
drugNoteType - unique note picklist types e.g.: Comprehensive Progress Admission Intubation
specialtyType - physician specialty picklist types e.g.: anesthesiology gastroenterology oncology
userType - who documented the drug from eCareManager user picklist types e.g.: eICU Physician, Nurse, Attending Physician
rxincluded - Does the Note have associated Rx data: True or False
writtenIneICU - Was the Note written in the eICU: True or False
drugName - name of the selected admission drug e.g.: POTASSIUM CHLORIDE/D5NS METAXALONE PRAVACHOL
drugDosage - dosage of the admission drug e.g.: 20.0000 400.000
drugUnit - picklist units of the admission drug e.g.: mg mg/kg patch
drugAdmitFrequency - picklist frequency with which the admission drug is administred e.g.: PRN twice a day at bedtime
drughiclseqno - a code representing the drug (hierarchical ingredient code list, HICL)
'''
filePath = "/data/fjsdata/physionet/eICU-CRD/admissionDrug.csv" 
data = pd.read_csv(filePath, sep=',')
data.head()

,admissiondrugid,patientunitstayid,drugoffset,drugenteredoffset,drugnotetype,specialtytype,usertype,rxincluded,writtenineicu,drugname,drugdosage,drugunit,drugadmitfrequency,drughiclseqno
0,1589228,242954,64,79,Admission,eCM Primary,THC Nurse,True,True,ELIQUIS ...,0.0,,,37792
1,2063596,243285,29,39,Admission,eCM Primary,THC Nurse,False,True,VICTOZA 2-PAK ...,0.0,,,36436
2,2063595,243285,29,39,Admission,eCM Primary,THC Nurse,False,True,POTASSIUM CHLORIDE ...,0.0,,,549
3,2063590,243285,29,39,Admission,eCM Primary,THC Nurse,False,True,CITALOPRAM HBR ...,0.0,,,10321
4,2063594,243285,29,39,Admission,eCM Primary,THC Nurse,False,True,OMEPRAZOLE ...,0.0,,,4673

In [9]:
'''
Table: admissionDx
admitDxName
admitDxText
'''
filePath = "/data/fjsdata/physionet/eICU-CRD/admissionDx.csv" 
data = pd.read_csv(filePath, sep=',')
data.head()

,admissiondxid,patientunitstayid,admitdxenteredoffset,admitdxpath,admitdxname,admitdxtext
0,8023778,2900217,62,admission diagnosis|Operative Organ Systems|Or...,Cardiovascular,Cardiovascular
1,8023777,2900217,62,admission diagnosis|Was the patient admitted f...,Yes,Yes
2,8023779,2900217,62,admission diagnosis|All Diagnosis|Operative|Di...,Aortic and Mitral valve replacement,Aortic and Mitral valve replacement
3,7929318,2900240,53,admission diagnosis|Non-operative Organ System...,Gastrointestinal,Gastrointestinal
4,7929317,2900240,53,admission diagnosis|Was the patient admitted f...,No,No

In [10]:
'''
Table: allergy
allergyEnteredOffset
allergyNoteType
specialtyType
userType
rxIncluded
writtenIneICU
drugName
allergyType
allergyName
drugHiclSeqno
'''
filePath = "/data/fjsdata/physionet/eICU-CRD/allergy.csv" 
data = pd.read_csv(filePath, sep=',')
data.head()

,allergyid,patientunitstayid,allergyoffset,allergyenteredoffset,allergynotetype,specialtytype,usertype,rxincluded,writtenineicu,drugname,allergytype,allergyname,drughiclseqno
0,378178,242070,3,3,Daily Progress,eCM Primary,Other,False,True,NaN,Non Drug,Red Dye ...,NaN
1,298537,242070,23,63,Admission,eCM Primary,THC Nurse,False,True,NaN,Non Drug,Red Dye ...,NaN
2,378177,242070,3,3,Daily Progress,eCM Primary,Other,False,True,NaN,Non Drug,Tape ...,NaN
3,298536,242070,23,63,Admission,eCM Primary,THC Nurse,False,True,NaN,Non Drug,Tape ...,NaN
4,385834,242083,1316,1319,Comprehensive Progress,eCM Primary,THC Nurse,False,True,NaN,Non Drug,Lisinopril ...,NaN

In [11]:
'''
Table: patient
allergyEnteredOffset
allergyNoteType
specialtyType
userType
rxIncluded
writtenIneICU
drugName
allergyType
allergyName
drugHiclSeqno
'''
filePath = "/data/fjsdata/physionet/eICU-CRD/patient.csv" 
data = pd.read_csv(filePath, sep=',')
data.head()

,patientunitstayid,patienthealthsystemstayid,gender,age,ethnicity,hospitalid,wardid,apacheadmissiondx,admissionheight,hospitaladmittime24,...,unitadmitsource,unitvisitnumber,unitstaytype,admissionweight,dischargeweight,unitdischargetime24,unitdischargeoffset,unitdischargelocation,unitdischargestatus,uniquepid
0,141168,128919,Female,70,Caucasian,59,91,"Rhythm disturbance (atrial, supraventricular)",152.4,15:54:00,...,Direct Admit,1,admit,84.3,85.8,03:50:00,3596,Death,Expired,002-34851
1,141178,128927,Female,52,Caucasian,60,83,NaN,162.6,08:56:00,...,Emergency Department,1,admit,54.4,54.4,09:18:00,8,Step-Down Unit (SDU),Alive,002-33870
2,141179,128927,Female,52,Caucasian,60,83,NaN,162.6,08:56:00,...,ICU to SDU,2,stepdown/other,NaN,60.4,19:20:00,2042,Home,Alive,002-33870
3,141194,128941,Male,68,Caucasian,73,92,"Sepsis, renal/UTI (including bladder)",180.3,18:18:40,...,Floor,1,admit,73.9,76.7,15:31:00,4813,Floor,Alive,002-5276
4,141196,128943,Male,71,Caucasian,67,109,NaN,162.6,20:21:00,...,ICU to SDU,2,stepdown/other,NaN,63.2,22:23:00,1463,Floor,Alive,002-37665